wip

diff --git a/dataset-runners/testing/hfb/run_synthseg b/dataset-runners/testing/hfb/run_synthseg
--- a/dataset-runners/testing/hfb/run_synthseg
+++ b/dataset-runners/testing/hfb/run_synthseg
@@ -22,46 +22,33 @@ T1_FN="T1.nii.gz"
 FL_FN=""
 
 #-------------------------------------------------------------------------------
-### CONFIG ###
-#-------------------------------------------------------------------------------
-
-### standard variables ###
-LIST_DIR=${OUT_DIR}/lists
-LOG_DIR=${OUT_DIR}/logs
-LIST_FN=${LIST_DIR}/subject_list.txt
-SYNTHSEG_SIF="${BLT_CONTAINER_DIR}/synthseg.sif"
-
-### checks and paths ###
-
-if [[ $# -ne 1 ]]; then
-  echo "USAGE ERROR"
-  exit 1
-fi
-
-if [[ -z "${MODULEPATH}" ]]; then
- echo "using apptainer/singularity on path"
-else
-  module --force purge
-  module load StdEnv/2023
-  module load apptainer/1.3.4
-fi
-
-for var in BLT_CONTAINER_DIR; do
-  if [[ -z "${!var}" ]]; then
-    echo "ERROR: $var not set"
-    exit 1
-  fi
-done
-
-if [[ ! -f ${SYNTHSEG_SIF} ]]; then
-  echo "ERROR: ${SYNTHSEG_SIF} not found"
-  exit 1
-fi
-
-
-#-------------------------------------------------------------------------------
 ### FUNCTIONS ###
 #-------------------------------------------------------------------------------
+
+function setup_environment()
+{
+  ### standard variables ###
+  LIST_DIR=${OUT_DIR}/lists
+  LOG_DIR=${OUT_DIR}/logs
+  LIST_FN=${LIST_DIR}/subject_list.txt
+  SYNTHSEG_SIF="${BLT_CONTAINER_DIR}/synthseg.sif"
+
+  ### checks and paths ###
+
+  if [[ $# -ne 1 ]]; then
+    echo "USAGE ERROR"
+    exit 1
+  fi
+
+  for var in BLT_CONTAINER_DIR; do
+    if [[ -z "${!var}" ]]; then
+      echo "ERROR: $var not set"
+      exit 1
+    fi
+  done
+
+  export PATH=${PATH}:${BRAINLAB_DIR}/wrapper-scripts/bash/core
+}
 
 function prep_dir
 {
@@ -80,18 +67,10 @@ function prep_dir
  
 function run_synthseg
 {
-  local modality=$1
-  local input_fn=$2
-  local output_fn=$3
+  local input_fn=$1
+  local output_fn=$2
 
-  if [[ -f "${IN_DIR}/${SUB_ID}/${input_fn}" ]]; then  
-    apptainer run --cleanenv --contain \
-      --bind "${IN_DIR}:/input" --bind "${OUT_DIR}:/output" \
-      --pwd / "${SYNTHSEG_SIF}" \
-      --i "/input/${SUB_ID}/${input_fn}" \
-      --o "/output/${SUB_ID}/${output_fn}" \
-      --threads "${NUM_THREADS}"
-  fi
+  blt_run_synthseg ${input_fn} ${output_fn} ${NUM_THREADS}
 }
 
 
@@ -99,15 +78,22 @@ function run_synthseg
 ### PROCESSING ###
 #-------------------------------------------------------------------------------
 
+setup_environment "$@"
 
 IDX=$1
 if [[ ${IDX} -eq 0 ]]; then
   prep_dir
 else
   SUB_ID=$(cat ${LIST_FN} | head -n ${IDX} | tail -n 1)
-  
-  run_synthseg "T1" "$T1_FN" "T1_synthseg.nii.gz"
-  run_synthseg "FLAIR" "$FL_FN" "FLAIR_synthseg.nii.gz"
+
+  if [[ -f ${IN_DIR}/${SUB_ID}/${T1_FN} ]]; then
+    run_synthseg ${IN_DIR}/${SUB_ID}/${T1_FN} ${OUT_DIR}/${SUB_ID}/T1_synthseg.nii.gz
+  fi
+
+  if [[ -f ${IN_DIR}/${SUB_ID}/${FL_FN} ]]; then
+    run_synthseg ${IN_DIR}/${SUB_ID}/${FL_FN} ${OUT_DIR}/${SUB_ID}/FLAIR_synthseg.nii.gz
+  fi
+
 fi
 
 #-------------------------------------------------------------------------------
diff --git a/wrapper-scripts/bash/core/blt_run_icvmapper b/wrapper-scripts/bash/core/blt_run_icvmapper
--- a/wrapper-scripts/bash/core/blt_run_icvmapper
+++ b/wrapper-scripts/bash/core/blt_run_icvmapper
@@ -3,89 +3,101 @@
 #===============================================================================
 ### REQUIREMENTS ###
 #===============================================================================
-
-# BRAINLAB_DIR and BLT_CONTAINER_DIR defined
-# FSL (cpgeom)
-# apptainer (or singularity symlinked to apptainer)
+# BRAINLAB_DIR and BLT_CONTAINER_DIR must be defined
+# Requires FSL (cpgeom), and apptainer (or singularity linked to apptainer)
 
 #-------------------------------------------------------------------------------
-### USAGE ###
+### FUNCTIONS ###
 #-------------------------------------------------------------------------------
 
-if [[ $# -lt 2 ]]; then
+function usage()
+{
   echo ""
   echo "Usage:"
-  echo "  $(basename $0) <OUT_DIR> <T1_IMAGE> [ICVMAPPER_OPTS]"
-  echo "Example:"
-  echo "  $(basename $0) SUB_DIR T1.nii.gz -b --thr 0.4"
+  echo "  $(basename "$0") <OUT_DIR> <T1_IMAGE> [ICVMAPPER_OPTS]"
   echo "" 
-  exit 1
-fi
+}
 
-#-------------------------------------------------------------------------------
-### CONFIG ###
-#-------------------------------------------------------------------------------
-
-OUT_DIR=$1
-T1=$2
-ICVMAPPER_OPTS=${@:3}
-
-for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
-  if [[ -z "${!var}" ]]; then
-    echo "ERROR: $var not set"
+function setup_environment()
+{
+  if [[ $# -lt 2 ]]; then
+    usage
     exit 1
   fi
-done
 
-if [[ -z "${MODULEPATH}" ]]; then
- echo "using fsl/apptainer on path"
-else
-  module --force purge
-  module load StdEnv/2020
-  module load apptainer/1.2.4
-  module load gcc/9.3.0
-  module load fsl/6.0.4
-fi
+  OUT_DIR=$1
+  T1_IMAGE=$2
+  ICVMAPPER_OPTS="${@:3}"
 
-export PATH=${PATH}:${BRAINLAB_DIR}/core-tools/bash
+  for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
+    if [[ -z "${!var:-}" ]]; then
+      echo "ERROR: $var not set"
+      exit 1
+    fi
+  done
 
-ICVMAPPER_SIF="${BLT_CONTAINER_DIR}/icvmapper.sif"
-if [[ ! -f ${ICVMAPPER_SIF} ]]; then
-  echo "ERROR: ${ICVMAPPER_SIF} not found"
-  exit 1
-fi
+  if [[ ! -f "$T1_IMAGE" ]]; then
+    echo "ERROR: T1 image '$T1_IMAGE' not found"
+    exit 1
+  fi
 
+  if [[ -z "${MODULEPATH:-}" ]]; then
+    echo "Using Apptainer/FSL on path"
+  else
+    module --force purge
+    module load StdEnv/2020
+    module load apptainer/1.2.4
+    module load gcc/9.3.0
+    module load fsl/6.0.4
+  fi
+
+  export PATH="${PATH}:${BRAINLAB_DIR}/core-tools/bash"
+
+  ICVMAPPER_SIF="${BLT_CONTAINER_DIR}/icvmapper.sif"
+  if [[ ! -f "${ICVMAPPER_SIF}" ]]; then
+    echo "ERROR: ${ICVMAPPER_SIF} not found"
+    exit 1
+  fi
+}
+
+function run_icvmapper()
+{
+  local abs_out=$(realpath -m "${OUT_DIR}")
+  mkdir -p "${abs_out}"
+
+  local tmp_dir=$(blt_create_tmpdir "${abs_out}" tmp_icv)
+  if [[ $? -ne 0 || -z "${tmp_dir}" ]]; then
+    echo "ERROR: bltCreateTmpDir failed"
+    exit 1
+  fi
+
+  echo "Temporary directory: ${tmp_dir}"
+
+  cp "${T1_IMAGE}" "${tmp_dir}/T1.nii.gz"
+
+  apptainer exec --cleanenv --contain \
+    --bind "${tmp_dir}:/data" \
+    "${ICVMAPPER_SIF}" icvmapper seg_icv \
+    -t1 /data/T1.nii.gz \
+    -o /data/HfB_icvmapper.nii.gz \
+    ${ICVMAPPER_OPTS}
+
+  cp "${tmp_dir}/HfB_icvmapper.nii.gz" "${abs_out}/"
+
+  cp "$(find "${tmp_dir}" -name "*pred_prob.nii.gz")" \
+    "${abs_out}/HfB_icvmapper_prob.nii.gz"
+
+  fslcpgeom "${T1_IMAGE}" "${abs_out}/HfB_icvmapper_prob.nii.gz"
+  fslcpgeom "${T1_IMAGE}" "${abs_out}/HfB_icvmapper.nii.gz"
+
+  rm -rf "${tmp_dir}"
+}
 
 #-------------------------------------------------------------------------------
 ### PROCESSING ###
 #-------------------------------------------------------------------------------
 
-TMP_DIR=$(bltCreateTmpDir ${OUT_DIR} tmp_icv)
-
-if [[ $? -ne 0 ]]; then
-  echo "ERROR: bltCreateTmpDir failed"
-  exit 1
-fi
-echo ${TMP_DIR}
-
-cp ${T1} ${TMP_DIR}/T1.nii.gz
-
-apptainer exec --cleanenv --contain \
-  --bind ${TMP_DIR}:/data  \
-  ${ICVMAPPER_SIF} icvmapper seg_icv \
-  -t1 /data/T1.nii.gz \
-  -o /data/icvHfB.nii.gz \
-  ${ICVMAPPER_OPTS}
-  
-cp ${TMP_DIR}/icvHfB.nii.gz ${OUT_DIR}/
-
-cp $(find ${TMP_DIR} -name "*pred_prob.nii.gz") \
-  ${OUT_DIR}/icvHfB_prob.nii.gz
-  
-fslcpgeom ${T1} ${OUT_DIR}/icvHfB_prob.nii.gz
-fslcpgeom ${T1} ${OUT_DIR}/icvHfB.nii.gz  
-
-rm -rf ${TMP_DIR}
+setup_environment "$@"
+run_icvmapper
 
 #-------------------------------------------------------------------------------
-
diff --git a/wrapper-scripts/bash/core/blt_run_synthseg b/wrapper-scripts/bash/core/blt_run_synthseg
--- a/wrapper-scripts/bash/core/blt_run_synthseg
+++ b/wrapper-scripts/bash/core/blt_run_synthseg
@@ -15,19 +15,20 @@ function usage()
   echo ""
   echo "Usage:"
   echo "  $(basename $0) <input_fn> <output_fn> <num_threads> [options]"
+  echo ""
 }
 
-function config()
+function setup_environment()
 {
-  INPUT_FN=$1
-  OUTPUT_FN=$2
-  NUM_THREADS=$3;
-  OPTIONS="${@:4}"
-
   if [[ $# -lt 3 ]]; then
     usage
     exit 1
   fi
+
+  INPUT_FN=$1
+  OUTPUT_FN=$2
+  NUM_THREADS=$3;
+  OPTIONS=("${@:4}")
 
   if [[ -z "${MODULEPATH}" ]]; then
     echo "using apptainer/singularity on path"
@@ -61,25 +62,30 @@ function run_synthseg()
   local in_file=$(basename "${abs_input}")
   local out_file=$(basename "${abs_output}")
 
-  if [[ -f "${abs_input}" ]]; then  
-    apptainer run --cleanenv --contain \
-      --bind "${in_dir}:/input" --bind "${out_dir}:/output" \
-      --pwd / "${SYNTHSEG_SIF}" \
-      --i "/input/${in_file}" \
-      --o "/output/${out_file}" \
-      --threads "${NUM_THREADS}" \
-      ${OPTIONS}
-  else
-    echo "ERROR: Input file '${input_fn}' not found"
+  if [[ ! -f "${abs_input}" ]]; then
+    echo "ERROR: input file '${abs_input}' not found"
     exit 1
   fi
+
+  if [[ ! -d "${out_dir}" ]]; then
+    echo "ERROR: output directory '${out_dir}' not found"
+    exit 1
+  fi
+
+  apptainer run --cleanenv --contain \
+    --bind "${in_dir}:/input" --bind "${out_dir}:/output" \
+    --pwd / "${SYNTHSEG_SIF}" \
+    --i /input/${in_file} \
+    --o /output/${out_file} \
+    --threads "${NUM_THREADS}"\
+    "${OPTIONS[@]}"
 }
 
 #-------------------------------------------------------------------------------
 ### PROCESSING ###
 #-------------------------------------------------------------------------------
 
-config "$@"
+setup_environment "$@"
 run_synthseg
 
 #-------------------------------------------------------------------------------
