wip

diff --git a/dataset-runners/testing/hfb/run_icvmapper b/dataset-runners/testing/hfb/run_icvmapper
--- a/dataset-runners/testing/hfb/run_icvmapper
+++ b/dataset-runners/testing/hfb/run_icvmapper
@@ -13,7 +13,7 @@
 #-------------------------------------------------------------------------------
 
 ### data variables ###
-BASE_DIR="${HOME}/tmp/test_datasets/dti/leducq"
+BASE_DIR="${SCRATCH}/leducq"
 IN_DIR="${BASE_DIR}/organized"
 OUT_DIR="${BASE_DIR}/derivatives/icvmapper"
 TMP_ROOT="${HOME}/tmp"
@@ -23,27 +23,29 @@ T1_FN=T1.nii.gz
 ### CONFIG ###
 #-------------------------------------------------------------------------------
 
-### standard variables ###
-LIST_DIR=${OUT_DIR}/lists
-LOG_DIR=${OUT_DIR}/logs
-LIST_FN=${LIST_DIR}/subject_list.txt
+function setup_environment()
+{
+  ### standard variables ###
+  LIST_DIR=${OUT_DIR}/lists
+  LOG_DIR=${OUT_DIR}/logs
+  LIST_FN=${LIST_DIR}/subject_list.txt
 
-### checks and paths ###
+  ### checks and paths ###
 
-if [[ $# -ne 1 ]]; then
-  echo "USAGE ERROR"
-  exit 1
-fi
-
-for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
-  if [[ -z "${!var}" ]]; then
-    echo "ERROR: $var not set"
+  if [[ $# -ne 1 ]]; then
+    echo "USAGE ERROR"
     exit 1
   fi
-done
 
-export PATH=${PATH}:${BRAINLAB_DIR}/wrapper-scripts/bash/core
+  for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
+    if [[ -z "${!var}" ]]; then
+      echo "ERROR: $var not set"
+      exit 1
+    fi
+  done
 
+  export PATH=${PATH}:${BRAINLAB_DIR}/wrapper-scripts/bash/core
+}
 
 #-------------------------------------------------------------------------------
 ### FUNCTIONS ###
@@ -75,6 +77,8 @@ function run_icvmapper
 #-------------------------------------------------------------------------------
 ### PROCESSING ###
 #-------------------------------------------------------------------------------
+
+setup_environment "$@"
 
 IDX=$1
 if [[ ${IDX} -eq 0 ]]; then
diff --git a/wrapper-scripts/bash/core/blt_run_icvmapper b/wrapper-scripts/bash/core/blt_run_icvmapper
--- a/wrapper-scripts/bash/core/blt_run_icvmapper
+++ b/wrapper-scripts/bash/core/blt_run_icvmapper
@@ -27,7 +27,7 @@ function setup_environment()
 
   OUT_DIR=$1
   T1_IMAGE=$2
-  ICVMAPPER_OPTS="${@:3}"
+  OPTIONS=(${@:3})
 
   for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
     if [[ -z "${!var:-}" ]]; then
@@ -62,6 +62,12 @@ function setup_environment()
 
 function run_icvmapper()
 {
+
+  if [[ ! -f ${T1_IMAGE} ]]; then
+    echo "ERROR: T1 image '${T1_IMAGE}' not found"
+    exit 1
+  fi
+
   local abs_out=$(realpath -m "${OUT_DIR}")
   mkdir -p "${abs_out}"
 
@@ -80,7 +86,7 @@ function run_icvmapper()
     "${ICVMAPPER_SIF}" icvmapper seg_icv \
     -t1 /data/T1.nii.gz \
     -o /data/HfB_icvmapper.nii.gz \
-    ${ICVMAPPER_OPTS}
+     "${OPTIONS[@]}"
 
   cp "${tmp_dir}/HfB_icvmapper.nii.gz" "${abs_out}/"
 
diff --git a/wrapper-scripts/bash/dti/dwi_preprocess b/wrapper-scripts/bash/dti/dwi_preprocess
--- a/wrapper-scripts/bash/dti/dwi_preprocess
+++ b/wrapper-scripts/bash/dti/dwi_preprocess
@@ -42,6 +42,13 @@ JSON_AP=${IN_DIR}/${SUB_ID}/${DWI_PA_PFX}.json
 DWI_PA=${IN_DIR}/${SUB_ID}/${DWI_PA_PFX}.nii.gz
 JSON_PA=${IN_DIR}/${SUB_ID}/${DWI_PA_PFX}.json
 
+### checks and paths ###
+if [[ $# -ne 1 ]]; then
+  echo "USAGE ERROR"
+  exit 1
+fi
+
+
 #-------------------------------------------------------------------------------
 ### FUNCTIONS ###
 #-------------------------------------------------------------------------------
