wip

diff --git a/dataset-runners/testing/hfb/run_icvmapper b/dataset-runners/testing/hfb/run_icvmapper
--- a/dataset-runners/testing/hfb/run_icvmapper
+++ b/dataset-runners/testing/hfb/run_icvmapper
@@ -1,72 +1,43 @@
 #!/bin/bash
 
-#-------------------------------------------------------------------------------
+#===============================================================================
 ### REQUIREMENTS ###
-#-------------------------------------------------------------------------------
+#===============================================================================
 
 # BRAINLAB_DIR, BLT_CONTAINER_DIR defined
-# apptainer/singularity
+# apptainer (or singularity symlinked to apptainer)
 # FSL (fslcpgeom)
 
 #-------------------------------------------------------------------------------
-### SETUP ###
+### VARIABLES ###
 #-------------------------------------------------------------------------------
 
 ### data variables ###
-root_dir="${SCRATCH}"
-in_dir="${root_dir}/organized"
-out_dir="${root_dir}/derivatives/icvmapper"
-tmp_root="${SCRATCH}/tmp"
-t1_fn=T1.nii.gz
+BASE_DIR="${HOME}/tmp/test_datasets/dti/leducq"
+IN_DIR="${BASE_DIR}/organized"
+OUT_DIR="${BASE_DIR}/derivatives/icvmapper"
+TMP_ROOT="${HOME}/tmp"
+T1_FN=T1.nii.gz
 
 #-------------------------------------------------------------------------------
 ### CONFIG ###
 #-------------------------------------------------------------------------------
 
 ### standard variables ###
-list_dir=${out_dir}/lists
-log_dir=${out_dir}/logs
-list_fn=${list_dir}/subject_list.txt
-icvmapper_sif="${BLT_CONTAINER_DIR}/icvmapper.sif"
+LIST_DIR=${OUT_DIR}/lists
+LOG_DIR=${OUT_DIR}/logs
+LIST_FN=${LIST_DIR}/subject_list.txt
 
-### path to required software ###
-if [[ -z "${MODULEPATH}" ]]; then
- echo "using fsl/apptainer/singularity on path"
-else
-  module --force purge
-  module load StdEnv/2020
-  module load apptainer/1.2.4
-  module load gcc/9.3.0
-  module load fsl/6.0.4
-fi
+### checks and paths ###
 
-### use apptainer, or singularity if apptainer is not available ###
-if command -v apptainer &> /dev/null; then
-  container_tool=apptainer
-elif command -v singularity &> /dev/null; then
-  container_tool=singularity
-else
-  echo "ERROR: neither apptainer nor singularity found in PATH."
-  exit 1
-fi
+for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
+  if [[ -z "${!var}" ]]; then
+    echo "ERROR: $var not set"
+    exit 1
+  fi
+done
 
-### ensure BRAINLAB_DIR, BLT_CONTAINER_DIR defined ###
-if [[ -z "${BRAINLAB_DIR}" ]]; then
-  echo "ERROR: BRAINLAB_DIR not set"
-  exit 1
-elif [[ -z "${BLT_CONTAINER_DIR}" ]]; then
-  echo "ERROR: BLT_CONTAINER_DIR not set"
-  exit 1
-fi
-
-### path to repo tools ###
 export PATH=${PATH}:${BRAINLAB_DIR}/wrapper-scripts/bash/core
-
-### ensure icvmapper.sif exists ###
-if [[ ! -f ${icvmapper_sif} ]]; then
-  echo "ERROR: ${icvmapper_sif} not found"
-  exit 1
-fi
 
 #-------------------------------------------------------------------------------
 ### FUNCTIONS ###
@@ -76,22 +47,22 @@ function prep_dir
 {
   echo "Preparing directories..."
   
-  mkdir -p ${list_dir}
-  mkdir -p ${out_dir}
+  mkdir -p ${LIST_DIR}
+  mkdir -p ${OUT_DIR}
 
-  rm -f ${list_fn}
-  $(cd ${in_dir}; ls -d * | grep -Ev "lists" | grep -Ev "logs" > ${list_fn})
+  rm -f ${LIST_FN}
+  $(cd ${IN_DIR}; ls -d * | grep -Ev "lists" | grep -Ev "logs" > ${LIST_FN})
   while read -r line; do
-    sub_id=$(echo ${line} | cut -d'/' -f1)
-    mkdir -p ${out_dir}/${sub_id}
-  done < ${list_fn}
+    SUB_ID=$(echo ${line} | cut -d'/' -f1)
+    mkdir -p ${OUT_DIR}/${SUB_ID}
+  done < ${LIST_FN}
 }
  
 function icvmapper_t1
 {
   bltIcvmapper \
-    ${out_dir}/${sub_id} \
-    ${in_dir}/${sub_id}/${t1_fn} \
+    ${OUT_DIR}/${SUB_ID} \
+    ${IN_DIR}/${SUB_ID}/${T1_FN} \
     -b --thr 0.4
 }
 
@@ -103,14 +74,11 @@ if [[ $# -eq 0 ]]; then
   prep_dir
 elif [[ $# -eq 1 ]]; then
   ### get subject ID from the list ###
-  idx=$1
-  sub_id=$(cat ${list_fn} | head -n ${idx} | tail -n 1)
+  IDX=$1
+  SUB_ID=$(cat ${LIST_FN} | head -n ${IDX} | tail -n 1)
   
   ### run container for subject ID ###
   icvmapper_t1
 fi
 
 #-------------------------------------------------------------------------------
-
-
-
diff --git a/dataset-runners/testing/hfb/run_synthseg b/dataset-runners/testing/hfb/run_synthseg
--- a/dataset-runners/testing/hfb/run_synthseg
+++ b/dataset-runners/testing/hfb/run_synthseg
@@ -1,37 +1,38 @@
 #!/bin/bash
 
-#-------------------------------------------------------------------------------
+#===============================================================================
 ### REQUIREMENTS ###
-#-------------------------------------------------------------------------------
+#===============================================================================
 
 # BLT_CONTAINER_DIR defined (synthseg.sif)
-# apptainer/singularity
+# apptainer (or singularity symlinked to apptainer)
 
 #-------------------------------------------------------------------------------
-### SETUP ###
+### VARIABLES ###
 #-------------------------------------------------------------------------------
 
 ### script variables ###
-num_threads=8;
+NUM_THREADS=1;
 
 ### data variables ###
-root_dir="${SCRATCH}"
-in_dir="${root_dir}/organized"
-out_dir="${root_dir}/derivatives/synthseg"
-t1_fn="T1.nii.gz"
-fl_fn=""
+BASE_DIR="${HOME}/tmp/test_datasets/dti/leducq"
+IN_DIR="${BASE_DIR}/organized"
+OUT_DIR="${BASE_DIR}/derivatives/synthseg"
+T1_FN="T1.nii.gz"
+FL_FN=""
 
 #-------------------------------------------------------------------------------
 ### CONFIG ###
 #-------------------------------------------------------------------------------
 
 ### standard variables ###
-list_dir=${out_dir}/lists
-log_dir=${out_dir}/logs
-list_fn=${list_dir}/subject_list.txt
-synthseg_sif="${BLT_CONTAINER_DIR}/synthseg.sif"
+LIST_DIR=${OUT_DIR}/lists
+LOG_DIR=${OUT_DIR}/logs
+LIST_FN=${LIST_DIR}/subject_list.txt
+SYNTHSEG_SIF="${BLT_CONTAINER_DIR}/synthseg.sif"
 
-### path to required software ###
+### checks and paths ###
+
 if [[ -z "${MODULEPATH}" ]]; then
  echo "using apptainer/singularity on path"
 else
@@ -40,28 +41,17 @@ else
   module load apptainer/1.3.4
 fi
 
-### use apptainer, or singularity if apptainer is not available ###
-if command -v apptainer &> /dev/null; then
-  container_tool=apptainer
-elif command -v singularity &> /dev/null; then
-  container_tool=singularity
-else
-  echo "ERROR: neither apptainer nor singularity found in PATH."
+for var in BLT_CONTAINER_DIR; do
+  if [[ -z "${!var}" ]]; then
+    echo "ERROR: $var not set"
+    exit 1
+  fi
+done
+
+if [[ ! -f ${SYNTHSEG_SIF} ]]; then
+  echo "ERROR: ${SYNTHSEG_SIF} not found"
   exit 1
 fi
-
-### ensure BLT_CONTAINER_DIR defined ###
-if [[ -z "${BLT_CONTAINER_DIR}" ]]; then
-  echo "ERROR: BLT_CONTAINER_DIR not set"
-  exit 1
-fi
-
-### ensure synthseg.sif exists ###
-if [[ ! -f ${synthseg_sif} ]]; then
-  echo "ERROR: ${synthseg_sif} not found"
-  exit 1
-fi
-
 
 #-------------------------------------------------------------------------------
 ### FUNCTIONS ###
@@ -71,31 +61,35 @@ function prep_dir
 {
   echo "Preparing directories"
 
-  mkdir -p ${list_dir}
-  mkdir -p ${out_dir}
+  mkdir -p ${LIST_DIR}
+  mkdir -p ${OUT_DIR}
 
-  rm -f ${list_fn}
-  $(cd ${in_dir}; ls -d * | grep -Ev "lists" | grep -Ev "logs" > ${list_fn})
+  rm -f ${LIST_FN}
+  $(cd ${IN_DIR}; ls -d * | grep -Ev "lists" | grep -Ev "logs" > ${LIST_FN})
   while read -r line; do
-    sub_id=$(echo ${line} | cut -d'/' -f1)
-    mkdir -p ${out_dir}/${sub_id}
-  done < ${list_fn}  
+    SUB_ID=$(echo ${line} | cut -d'/' -f1)
+    mkdir -p ${OUT_DIR}/${SUB_ID}
+  done < ${LIST_FN}  
 }
  
 function run_synthseg
 {
-  if [[ -f ${in_dir}/${sub_id}/${t1_fn} ]]; then  
-    ${container_tool} run --cleanenv --contain --pwd / ${synthseg_sif} \
-      --i ${in_dir}/${sub_id}/${t1_fn} \
-      --o ${out_dir}/${sub_id}/T1_synthseg.nii.gz \
-      --threads ${num_threads} 
+  if [[ -f ${IN_DIR}/${SUB_ID}/${T1_FN} ]]; then  
+    apptainer run --cleanenv --contain \
+      --bind ${IN_DIR}:/input --bind ${OUT_DIR}:/output \
+      --pwd / ${SYNTHSEG_SIF} \
+      --i /input/${SUB_ID}/${T1_FN} \
+      --o /output/${SUB_ID}/T1_synthseg.nii.gz \
+      --threads ${NUM_THREADS} 
   fi
 
-  if [[ -f ${in_dir}/${sub_id}/${fl_fn} ]]; then  
-    ${container_tool} run --cleanenv --contain --pwd / ${synthseg_sif} \
-      --i ${in_dir}/${sub_id}/${fl_fn} \
-      --o ${out_dir}/${sub_id}/FLAIR_synthseg.nii.gz \
-      --threads ${num_threads} 
+  if [[ -f ${IN_DIR}/${SUB_ID}/${FL_FN} ]]; then  
+    apptainer run --cleanenv --contain \
+      --bind ${IN_DIR}:/input --bind ${OUT_DIR}:/output \
+      --pwd / ${SYNTHSEG_SIF} \
+      --i /input/${SUB_ID}/${FL_FN} \
+      --o /output/${SUB_ID}/FLAIR_synthseg.nii.gz \
+      --threads ${NUM_THREADS}
   fi
 }
 
@@ -109,8 +103,8 @@ if [[ $# -eq 0 ]]; then
 elif [[ $# -eq 1 ]]; then
 
   ### get subject ID from the list ###
-  idx=$1
-  sub_id=$(cat ${list_fn} | head -n ${idx} | tail -n 1)
+  IDX=$1
+  SUB_ID=$(cat ${LIST_FN} | head -n ${IDX} | tail -n 1)
   
   ### run container for subject ID ###
   run_synthseg
@@ -118,6 +112,3 @@ elif [[ $# -eq 1 ]]; then
 fi
 
 #-------------------------------------------------------------------------------
-
-
-
diff --git a/wrapper-scripts/bash/core/bltIcvmapper b/wrapper-scripts/bash/core/bltIcvmapper
--- a/wrapper-scripts/bash/core/bltIcvmapper
+++ b/wrapper-scripts/bash/core/bltIcvmapper
@@ -1,77 +1,91 @@
 #!/bin/bash
 
-#-------------------------------------------------------------------------------
+#===============================================================================
 ### REQUIREMENTS ###
-#-------------------------------------------------------------------------------
+#===============================================================================
 
 # BRAINLAB_DIR and BLT_CONTAINER_DIR defined
 # FSL (cpgeom)
+# apptainer (or singularity symlinked to apptainer)
 
 #-------------------------------------------------------------------------------
 ### USAGE ###
 #-------------------------------------------------------------------------------
+
 if [[ $# -lt 2 ]]; then
   echo ""
   echo "Usage:"
-  echo "  $(basename $0) <output_dir> <t1_image> [icvmapper_opts]"
+  echo "  $(basename $0) <OUT_DIR> <T1_IMAGE> [ICVMAPPER_OPTS]"
   echo "Example:"
-  echo "  $(basename $0) sub_dir T1.nii.gz -b --thr 0.4"
+  echo "  $(basename $0) SUB_DIR T1.nii.gz -b --thr 0.4"
   echo "" 
   exit 1
 fi
 
 #-------------------------------------------------------------------------------
-### SETUP ###
+### CONFIG ###
 #-------------------------------------------------------------------------------
 
-out_dir=$1
-t1=$2
-icvmapper_opts=${@:3}
+OUT_DIR=$1
+T1=$2
+ICVMAPPER_OPTS=${@:3}
 
+for var in BRAINLAB_DIR BLT_CONTAINER_DIR; do
+  if [[ -z "${!var}" ]]; then
+    echo "ERROR: $var not set"
+    exit 1
+  fi
+done
+
+if [[ -z "${MODULEPATH}" ]]; then
+ echo "using fsl/apptainer on path"
+else
+  module --force purge
+  module load StdEnv/2020
+  module load apptainer/1.2.4
+  module load gcc/9.3.0
+  module load fsl/6.0.4
+fi
 
 export PATH=${PATH}:${BRAINLAB_DIR}/core-tools/bash
-icvmapper_sif=${BLT_CONTAINER_DIR}/icvmapper.sif
 
-### use apptainer, or singularity if apptainer is not available ###
-if command -v apptainer &> /dev/null; then
-  container_tool=apptainer
-elif command -v singularity &> /dev/null; then
-  container_tool=singularity
-else
-  echo "ERROR: neither apptainer nor singularity found in PATH."
+ICVMAPPER_SIF="${BLT_CONTAINER_DIR}/icvmapper.sif"
+if [[ ! -f ${ICVMAPPER_SIF} ]]; then
+  echo "ERROR: ${ICVMAPPER_SIF} not found"
   exit 1
 fi
+
 
 #-------------------------------------------------------------------------------
 ### PROCESSING ###
 #-------------------------------------------------------------------------------
 
-tmp_dir=$(bltCreateTmpDir ${out_dir} tmp_icv)
+TMP_DIR=$(bltCreateTmpDir ${OUT_DIR} tmp_icv)
 
 if [[ $? -ne 0 ]]; then
   echo "ERROR: bltCreateTmpDir failed"
   exit 1
 fi
-echo ${tmp_dir}
+echo ${TMP_DIR}
 
-cp ${t1} ${tmp_dir}/T1.nii.gz
-t1=${tmp_dir}/T1.nii.gz
+cp ${T1} ${TMP_DIR}/T1.nii.gz
 
-${container_tool} exec --cleanenv --contain \
-  -B ${HOME} -B ${out_dir} \
-  ${icvmapper_sif} icvmapper seg_icv \
-  -t1 ${t1} \
-  -o ${tmp_dir}/icvHfB.nii.gz \
-  ${icvmapper_opts}
+apptainer exec --cleanenv --contain \
+  --bind ${TMP_DIR}:/data  \
+  ${ICVMAPPER_SIF} icvmapper seg_icv \
+  -t1 /data/T1.nii.gz \
+  -o /data/icvHfB.nii.gz \
+  ${ICVMAPPER_OPTS}
   
-cp ${tmp_dir}/icvHfB.nii.gz ${out_dir}/
+cp ${TMP_DIR}/icvHfB.nii.gz ${OUT_DIR}/
 
-cp $(find ${tmp_dir} -name "*pred_prob.nii.gz") \
-  ${out_dir}/icvHfB_prob.nii.gz
+cp $(find ${TMP_DIR} -name "*pred_prob.nii.gz") \
+  ${OUT_DIR}/icvHfB_prob.nii.gz
   
-fslcpgeom ${t1} ${out_dir}/icvHfB_prob.nii.gz
-fslcpgeom ${t1} ${out_dir}/icvHfB.nii.gz  
+fslcpgeom ${T1} ${OUT_DIR}/icvHfB_prob.nii.gz
+fslcpgeom ${T1} ${OUT_DIR}/icvHfB.nii.gz  
 
-rm -rf ${tmp_dir}
+rm -rf ${TMP_DIR}
 
 #-------------------------------------------------------------------------------
+
