wip

diff --git a/dataset-runners/testing/hfb/run_icvmapper b/dataset-runners/testing/hfb/run_icvmapper
--- a/dataset-runners/testing/hfb/run_icvmapper
+++ b/dataset-runners/testing/hfb/run_icvmapper
@@ -4,7 +4,7 @@
 ### REQUIREMENTS ###
 #-------------------------------------------------------------------------------
 
-# BRAINLAB_DIR defined
+# BRAINLAB_DIR, BLT_CONTAINER_DIR defined
 # apptainer/singularity
 # FSL (fslcpgeom)
 
@@ -12,13 +12,10 @@
 ### SETUP ###
 #-------------------------------------------------------------------------------
 
-### script variables ###
-icvmapper_sif="${HOME}/work/containers/lab/icvmapper.sif"
-
 ### data variables ###
 root_dir="${HOME}/tmp/test_datasets/dti/adni"
 in_dir=${root_dir}/organized
-out_dir=${root_dir}/derivatives/standard
+out_dir=${root_dir}/derivatives/icvmapper
 tmp_root=${HOME}/tmp
 t1_fn=T1.nii.gz
 
@@ -30,9 +27,35 @@ t1_fn=T1.nii.gz
 list_dir=${out_dir}/lists
 log_dir=${out_dir}/logs
 list_fn=${list_dir}/subject_list.txt
+icvmapper_sif="${BLT_CONTAINER_DIR}/icvmapper.sif"
+
+### use apptainer, or singularity if apptainer is not available ###
+if command -v apptainer &> /dev/null; then
+  container_tool=apptainer
+elif command -v singularity &> /dev/null; then
+  container_tool=singularity
+else
+  echo "ERROR: neither apptainer nor singularity found in PATH."
+  exit 1
+fi
+
+### ensure BRAINLAB_DIR, BLT_CONTAINER_DIR defined ###
+if [[ -z "${BRAINLAB_DIR}" ]]; then
+  echo "ERROR: BRAINLAB_DIR not set"
+  exit 1
+elif [[ -z "${BLT_CONTAINER_DIR}" ]]; then
+  echo "ERROR: BLT_CONTAINER_DIR not set"
+  exit 1
+fi
 
 ### path to repo tools ###
 export PATH=${PATH}:${BRAINLAB_DIR}/wrapper-scripts/bash/core
+
+### ensure icvmapper.sif exists ###
+if [[ ! -f ${icvmapper_sif} ]]; then
+  echo "ERROR: ${icvmapper_sif} not found"
+  exit 1
+fi
 
 ### path to required software ###
 if [[ -z "${MODULEPATH}" ]]; then
@@ -58,19 +81,14 @@ function prep_dir
     sub_id=$(echo ${line} | cut -d'/' -f1)
     mkdir -p ${out_dir}/${sub_id}
   done < ${list_fn}
-  
-  num_subs=$(cat ${list_fn} | wc -l)
-  touch ${list_dir}/subject_list_n${num_subs}.txt
 }
  
-
 function icvmapper_t1
 {
   bltIcvmapper \
     ${out_dir}/${sub_id} \
     ${in_dir}/${sub_id}/${t1_fn} \
-    ${icvmapper_sif} \
-    -b --thr 0.4 -n 3
+    -b --thr 0.4
 }
 
 #-------------------------------------------------------------------------------
@@ -78,28 +96,14 @@ function icvmapper_t1
 #-------------------------------------------------------------------------------
 
 if [[ $# -eq 0 ]]; then
-  echo "icvmapper_sif: $(ls ${icvmapper_sif})"
- #bltCreateTmpDir
   prep_dir
 elif [[ $# -eq 1 ]]; then
-
   ### get subject ID from the list ###
   idx=$1
   sub_id=$(cat ${list_fn} | head -n ${idx} | tail -n 1)
   
-  ### use apptainer, or singularity if apptainer is not available ###
-  if command -v apptainer &> /dev/null; then
-    container_tool=apptainer
-  elif command -v singularity &> /dev/null; then
-    container_tool=singularity
-  else
-    echo "ERROR: neither apptainer nor singularity found in PATH."
-    exit 1
-  fi
-
   ### run container for subject ID ###
   icvmapper_t1
-
 fi
 
 #-------------------------------------------------------------------------------
diff --git a/dataset-runners/testing/hfb/run_synthseg b/dataset-runners/testing/hfb/run_synthseg
--- a/dataset-runners/testing/hfb/run_synthseg
+++ b/dataset-runners/testing/hfb/run_synthseg
@@ -4,6 +4,7 @@
 ### REQUIREMENTS ###
 #-------------------------------------------------------------------------------
 
+# BLT_CONTAINER_DIR defined (synthseg.sif)
 # apptainer/singularity
 
 #-------------------------------------------------------------------------------
@@ -11,15 +12,14 @@
 #-------------------------------------------------------------------------------
 
 ### script variables ###
-brainlab_dir="${HOME}/work/code/brainlab"
-synthseg_sif="${HOME}/work/containers/synthseg/v2.0/synthseg.sif"
 num_threads=1;
 
 ### data variables ###
 root_dir="${HOME}/tmp/test_datasets/dti/adni"
-in_dir=${root_dir}/organized
-out_dir=${root_dir}/derivatives/standard
-t1_fn=T1.nii.gz
+in_dir="${root_dir}/organized"
+out_dir="${root_dir}/derivatives/synthseg"
+t1_fn="T1.nii.gz"
+fl_fn=""
 
 #-------------------------------------------------------------------------------
 ### CONFIG ###
@@ -29,14 +29,37 @@ t1_fn=T1.nii.gz
 list_dir=${out_dir}/lists
 log_dir=${out_dir}/logs
 list_fn=${list_dir}/subject_list.txt
+synthseg_sif="${BLT_CONTAINER_DIR}/synthseg.sif"
 
+### use apptainer, or singularity if apptainer is not available ###
+if command -v apptainer &> /dev/null; then
+  container_tool=apptainer
+elif command -v singularity &> /dev/null; then
+  container_tool=singularity
+else
+  echo "ERROR: neither apptainer nor singularity found in PATH."
+  exit 1
+fi
 
 ### path to required software ###
 if [[ -z "${MODULEPATH}" ]]; then
-  module load apptainer/1.3.4
+ echo "using apptainer/singularity on path"
 else
-  echo "using apptainer/singularity on path"
+  module load apptainer/1.3.4
 fi
+
+### ensure BLT_CONTAINER_DIR defined ###
+if [[ -z "${BLT_CONTAINER_DIR}" ]]; then
+  echo "ERROR: BLT_CONTAINER_DIR not set"
+  exit 1
+fi
+
+### ensure synthseg.sif exists ###
+if [[ ! -f ${synthseg_sif} ]]; then
+  echo "ERROR: ${synthseg_sif} not found"
+  exit 1
+fi
+
 
 #-------------------------------------------------------------------------------
 ### FUNCTIONS ###
@@ -44,7 +67,7 @@ fi
 
 function prep_dir
 {
-  echo "Preparing directories..."
+  echo "Preparing directories"
 
   mkdir -p ${list_dir}
   mkdir -p ${out_dir}
@@ -54,18 +77,24 @@ function prep_dir
   while read -r line; do
     sub_id=$(echo ${line} | cut -d'/' -f1)
     mkdir -p ${out_dir}/${sub_id}
-  done < ${list_fn}
-  
-  num_subs=$(cat ${list_fn} | wc -l)
-  touch ${list_dir}/subject_list_n${num_subs}.txt
+  done < ${list_fn}  
 }
  
-function synthseg_t1
+function run_synthseg
 {
-  ${container_tool} run --pwd / ${synthseg_sif} \
-     --i ${in_dir}/${sub_id}/T1.nii.gz \
-     --o ${out_dir}/${sub_id}/T1_synthseg.nii.gz \
-     --threads ${num_threads} 
+  if [[ -f ${in_dir}/${sub_id}/${t1_fn} ]]; then  
+    ${container_tool} run --pwd / ${synthseg_sif} \
+      --i ${in_dir}/${sub_id}/${t1_fn} \
+      --o ${out_dir}/${sub_id}/T1_synthseg.nii.gz \
+      --threads ${num_threads} 
+  fi
+
+  if [[ -f ${in_dir}/${sub_id}/${fl_fn} ]]; then  
+    ${container_tool} run --pwd / ${synthseg_sif} \
+      --i ${in_dir}/${sub_id}/${fl_fn} \
+      --o ${out_dir}/${sub_id}/FLAIR_synthseg.nii.gz \
+      --threads ${num_threads} 
+  fi
 }
 
 #-------------------------------------------------------------------------------
@@ -73,7 +102,6 @@ function synthseg_t1
 #-------------------------------------------------------------------------------
 
 if [[ $# -eq 0 ]]; then
-  echo "synthseg_sif: $(ls ${synthseg_sif})"
   prep_dir
 elif [[ $# -eq 1 ]]; then
 
@@ -81,18 +109,8 @@ elif [[ $# -eq 1 ]]; then
   idx=$1
   sub_id=$(cat ${list_fn} | head -n ${idx} | tail -n 1)
   
-  ### use apptainer, or singularity if apptainer is not available ###
-  if command -v apptainer &> /dev/null; then
-    container_tool=apptainer
-  elif command -v singularity &> /dev/null; then
-    container_tool=singularity
-  else
-    echo "ERROR: neither apptainer nor singularity found in PATH."
-    exit 1
-  fi
-
   ### run container for subject ID ###
-  synthseg_t1
+  run_synthseg
 
 fi
 
